keys:
  - &nathan age17uexz24vml9jvnljxlzqqtshdddhgya3lg4mn744c8xtdnf9eaqq4dwf0p
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|txt)$
    key_groups:
    - age:
      - *nathan
  - path_regex: /dev/stdin$
    key_groups:
    - age:
      - *nathan
