[catppuccin-btop]
src.git = "https://github.com/catppuccin/btop"
fetch.github = "catppuccin/btop"

[catppuccin-godot]
src.git = "https://github.com/boranroni/godot-engine"
fetch.github = "boranroni/godot-engine"

[catppuccin-rofi]
src.git = "https://github.com/catppuccin/rofi"
fetch.github = "catppuccin/rofi"

[headlamp]
src.github = "kubernetes-sigs/headlamp"
src.prefix = "v"
fetch.url = "https://github.com/kubernetes-sigs/headlamp/releases/download/v$ver/Headlamp-$ver-linux-x64.AppImage"

[pkl-lsp]
src.github = "apple/pkl-lsp"
fetch.url = "https://github.com/apple/pkl-lsp/releases/download/$ver/pkl-lsp-$ver.jar"

[pkl-neovim]
src.git = "https://github.com/apple/pkl-neovim"
fetch.github = "apple/pkl-neovim"


[whichpy-nvim]
src.git = "https://github.com/neolooong/whichpy.nvim"
fetch.git = "https://github.com/neolooong/whichpy.nvim"


[nvim-treesitter]
src.git = "https://github.com/nvim-treesitter/nvim-treesitter"
src.branch = "main"
fetch.git = "https://github.com/nvim-treesitter/nvim-treesitter"

[tree-sitter-pkl]
src.git = "https://github.com/apple/tree-sitter-pkl"
fetch.git = "https://github.com/apple/tree-sitter-pkl"

[odl-agent-kit]
src.git = "https://github.com/mitodl/agent-kit.git"
fetch.git = "https://github.com/mitodl/agent-kit.git"
