# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  # boot.kernelPackages = pkgs.linuxPackages_6_14;
  boot.kernelPackages = pkgs.linuxPackages_latest;

  
  # Critical kernel parameters for Nvidia KMS and video memory preservation
  boot.kernelParams = [
    "nvidia-drm.modeset=1"                   # Allows for early modeset in init
    "nvidia.NVreg_PreserveVideoMemoryAllocations=1"  # Helps with suspend/resume, flicker
  ];

  # Ensure modules load in correct order
  boot.extraModprobeConfig = ''
    options nvidia-drm modeset=1
    softdep nvidia pre: nvidia-drm
  '';

  # Make sure all four nvidia modules are in the initrd
  boot.initrd.kernelModules = [
    "nvidia" 
    "nvidia_modeset" 
    "nvidia_uvm" 
    "nvidia_drm"
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f75907ab-9b04-4d20-83a9-d4900839e29e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5212-1BF7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0f0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
