# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin-btop = {
    pname = "catppuccin-btop";
    version = "f437574b600f1c6d932627050b15ff5153b58fa3";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "f437574b600f1c6d932627050b15ff5153b58fa3";
      fetchSubmodules = false;
      sha256 = "sha256-mEGZwScVPWGu+Vbtddc/sJ+mNdD2kKienGZVUcTSl+c=";
    };
    date = "2024-09-23";
  };
  catppuccin-godot = {
    pname = "catppuccin-godot";
    version = "62f50af79b40f36e00b27ce9d9baaccdf220d8e6";
    src = fetchFromGitHub {
      owner = "boranroni";
      repo = "godot-engine";
      rev = "62f50af79b40f36e00b27ce9d9baaccdf220d8e6";
      fetchSubmodules = false;
      sha256 = "sha256-ZnF7QefFV6mtpuVpMKNgNG0AyiUbk5439ZBvibJmQas=";
    };
    date = "2023-03-14";
  };
  catppuccin-rofi = {
    pname = "catppuccin-rofi";
    version = "71fb15577ccb091df2f4fc1f65710edbc61b5a53";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "rofi";
      rev = "71fb15577ccb091df2f4fc1f65710edbc61b5a53";
      fetchSubmodules = false;
      sha256 = "sha256-81eeFjwM/haPjIEWkZPp1JSDwhWbWDAuKtWiCg7P9Q0=";
    };
    date = "2025-07-19";
  };
  headlamp = {
    pname = "headlamp";
    version = "0.37.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/headlamp/releases/download/v0.37.0/Headlamp-0.37.0-linux-x64.AppImage";
      sha256 = "sha256-ix/gJ0cJ+NxJTYKSa/0Co+g+cxWdq+Zn6atq4L4TkKw=";
    };
  };
  pkl-lsp = {
    pname = "pkl-lsp";
    version = "0.5.1";
    src = fetchurl {
      url = "https://github.com/apple/pkl-lsp/releases/download/0.5.1/pkl-lsp-0.5.1.jar";
      sha256 = "sha256-oI//cGGle4glYjRBGfLZWuDozEqeQQ32HVZ4oM2NKT8=";
    };
  };
  pkl-neovim = {
    pname = "pkl-neovim";
    version = "512a2bce00f1541ff58e850a74b8671b84976f14";
    src = fetchFromGitHub {
      owner = "apple";
      repo = "pkl-neovim";
      rev = "512a2bce00f1541ff58e850a74b8671b84976f14";
      fetchSubmodules = false;
      sha256 = "sha256-jMC15yUpfB8j+aeTeNTOimPyOT9qxxD4uYymvhlcBAY=";
    };
    date = "2025-11-06";
  };
}
