# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin-btop = {
    pname = "catppuccin-btop";
    version = "f437574b600f1c6d932627050b15ff5153b58fa3";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "f437574b600f1c6d932627050b15ff5153b58fa3";
      fetchSubmodules = false;
      sha256 = "sha256-mEGZwScVPWGu+Vbtddc/sJ+mNdD2kKienGZVUcTSl+c=";
    };
    date = "2024-09-23";
  };
  catppuccin-godot = {
    pname = "catppuccin-godot";
    version = "62f50af79b40f36e00b27ce9d9baaccdf220d8e6";
    src = fetchFromGitHub {
      owner = "boranroni";
      repo = "godot-engine";
      rev = "62f50af79b40f36e00b27ce9d9baaccdf220d8e6";
      fetchSubmodules = false;
      sha256 = "sha256-ZnF7QefFV6mtpuVpMKNgNG0AyiUbk5439ZBvibJmQas=";
    };
    date = "2023-03-14";
  };
  catppuccin-rofi = {
    pname = "catppuccin-rofi";
    version = "71fb15577ccb091df2f4fc1f65710edbc61b5a53";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "rofi";
      rev = "71fb15577ccb091df2f4fc1f65710edbc61b5a53";
      fetchSubmodules = false;
      sha256 = "sha256-81eeFjwM/haPjIEWkZPp1JSDwhWbWDAuKtWiCg7P9Q0=";
    };
    date = "2025-07-19";
  };
  headlamp = {
    pname = "headlamp";
    version = "0.38.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/headlamp/releases/download/v0.38.0/Headlamp-0.38.0-linux-x64.AppImage";
      sha256 = "sha256-WIsr/lG+yAyoKITk7kka9HEw5nr0o2f4rKcIVf+trP4=";
    };
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "c5871d9d870c866fea9f271f1a3b3f29049a4793";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter";
      rev = "c5871d9d870c866fea9f271f1a3b3f29049a4793";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oXHJxYFDqZ72C/sJGSMFVwkRRCXipVjE+xz+5eeCX30=";
    };
    date = "2025-11-25";
  };
  pkl-lsp = {
    pname = "pkl-lsp";
    version = "0.5.1";
    src = fetchurl {
      url = "https://github.com/apple/pkl-lsp/releases/download/0.5.1/pkl-lsp-0.5.1.jar";
      sha256 = "sha256-oI//cGGle4glYjRBGfLZWuDozEqeQQ32HVZ4oM2NKT8=";
    };
  };
  pkl-neovim = {
    pname = "pkl-neovim";
    version = "fec35f648c21263cf81228cb8978ac0ad86a66da";
    src = fetchFromGitHub {
      owner = "apple";
      repo = "pkl-neovim";
      rev = "fec35f648c21263cf81228cb8978ac0ad86a66da";
      fetchSubmodules = false;
      sha256 = "sha256-Qg5ecegUUWnUPjZG5IcS2v1Vfm0ESIrfq6B4/aehzWo=";
    };
    date = "2025-11-21";
  };
  tree-sitter-pkl = {
    pname = "tree-sitter-pkl";
    version = "82f0e990b727374014371681457cc6ea5c3daa97";
    src = fetchgit {
      url = "https://github.com/apple/tree-sitter-pkl";
      rev = "82f0e990b727374014371681457cc6ea5c3daa97";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-USRl2LghA0e+shclJFp6HxDKJf6+txslMZiQ4pCfOvw=";
    };
    date = "2025-11-24";
  };
  whichpy-nvim = {
    pname = "whichpy-nvim";
    version = "4091361ed224e0e5ae92b2a5c412cb2ca7c26f65";
    src = fetchgit {
      url = "https://github.com/neolooong/whichpy.nvim";
      rev = "4091361ed224e0e5ae92b2a5c412cb2ca7c26f65";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ijeQjh+jAlKQRT4Wl5R0YpGSp/pd1uyXfWrsRCAumMY=";
    };
    date = "2025-05-13";
  };
}
