# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  catppuccin-btop = {
    pname = "catppuccin-btop";
    version = "f437574b600f1c6d932627050b15ff5153b58fa3";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "f437574b600f1c6d932627050b15ff5153b58fa3";
      fetchSubmodules = false;
      sha256 = "sha256-mEGZwScVPWGu+Vbtddc/sJ+mNdD2kKienGZVUcTSl+c=";
    };
    date = "2024-09-23";
  };
  catppuccin-godot = {
    pname = "catppuccin-godot";
    version = "62f50af79b40f36e00b27ce9d9baaccdf220d8e6";
    src = fetchFromGitHub {
      owner = "boranroni";
      repo = "godot-engine";
      rev = "62f50af79b40f36e00b27ce9d9baaccdf220d8e6";
      fetchSubmodules = false;
      sha256 = "sha256-ZnF7QefFV6mtpuVpMKNgNG0AyiUbk5439ZBvibJmQas=";
    };
    date = "2023-03-14";
  };
  catppuccin-rofi = {
    pname = "catppuccin-rofi";
    version = "71fb15577ccb091df2f4fc1f65710edbc61b5a53";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "rofi";
      rev = "71fb15577ccb091df2f4fc1f65710edbc61b5a53";
      fetchSubmodules = false;
      sha256 = "sha256-81eeFjwM/haPjIEWkZPp1JSDwhWbWDAuKtWiCg7P9Q0=";
    };
    date = "2025-07-19";
  };
  headlamp = {
    pname = "headlamp";
    version = "0.44.0";
    src = fetchurl {
      url = "https://github.com/kubernetes-sigs/headlamp/releases/download/v0.44.0/Headlamp-0.44.0-linux-x64.AppImage";
      sha256 = "sha256-w0wMChMAkQrZroWQqH5tKhJH4z2ecMdS7ALxohJmEiw=";
    };
  };
  lean-ctx = {
    pname = "lean-ctx";
    version = "3.9.18";
    src = fetchurl {
      url = "https://github.com/yvgude/lean-ctx/releases/download/v3.9.18/lean-ctx-3.9.18-source.tar.gz";
      sha256 = "sha256-EpJ3b5VJMHzz/q3pXXVBG6b84kqfltSgetYUaIRoY1A=";
    };
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "a1bcffc8095c142ad1f7a9671a4ae180333f9209";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter";
      rev = "a1bcffc8095c142ad1f7a9671a4ae180333f9209";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v52UOEN9ortmX0FMyGaRPLzHBk19iUn4+3QE16FxDAM=";
    };
    date = "2026-08-13";
  };
  odl-agent-kit = {
    pname = "odl-agent-kit";
    version = "2b5cc6826296a3f634cf00d7211c482c9d0c4075";
    src = fetchgit {
      url = "https://github.com/mitodl/agent-kit.git";
      rev = "2b5cc6826296a3f634cf00d7211c482c9d0c4075";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-jeSFEa1ePfdo/LO4mC4bBh925WO+hgqNVJFCdeNTWKM=";
    };
    date = "2026-08-13";
  };
  omnigraph = {
    pname = "omnigraph";
    version = "0.8.1";
    src = fetchurl {
      url = "https://github.com/ModernRelay/omnigraph/releases/download/v0.8.1/omnigraph-linux-x86_64.tar.gz";
      sha256 = "sha256-wl4rtTWIh+ZOM9MTU3DoDqIVpUYI33I9l9nKxnt/nj4=";
    };
  };
  pkl-lsp = {
    pname = "pkl-lsp";
    version = "0.8.0";
    src = fetchurl {
      url = "https://github.com/apple/pkl-lsp/releases/download/0.8.0/pkl-lsp-0.8.0.jar";
      sha256 = "sha256-BvneRaIap6Fr9cBSUTUh+YeTzZxXA2uTaPyteZ6WqP8=";
    };
  };
  pkl-neovim = {
    pname = "pkl-neovim";
    version = "7907b89958d06fa5a5dc72eeb26d8289605595c3";
    src = fetchFromGitHub {
      owner = "apple";
      repo = "pkl-neovim";
      rev = "7907b89958d06fa5a5dc72eeb26d8289605595c3";
      fetchSubmodules = false;
      sha256 = "sha256-RwBeVi3MK9svEIP4nYechHg9AZ1zygK2xlvjjGEE5EQ=";
    };
    date = "2026-07-09";
  };
  tree-sitter-pkl = {
    pname = "tree-sitter-pkl";
    version = "3486521eb1c2fcb3c9a5e88300215930ee515693";
    src = fetchgit {
      url = "https://github.com/apple/tree-sitter-pkl";
      rev = "3486521eb1c2fcb3c9a5e88300215930ee515693";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-bQNSSDVVi0kmsIlpmI+7LWf8/SrXylAyEju/DAahqzg=";
    };
    date = "2026-07-14";
  };
  whichpy-nvim = {
    pname = "whichpy-nvim";
    version = "96bc91d36d52fd64f1e5ab358c1b85f313c11628";
    src = fetchgit {
      url = "https://github.com/neolooong/whichpy.nvim";
      rev = "96bc91d36d52fd64f1e5ab358c1b85f313c11628";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-a4TqZ7wW5quTvZ1TgTdpzm4K2hM6+fsvLZgVzl8USfU=";
    };
    date = "2026-05-09";
  };
}
